### PR TITLE
Validation

### PR DESCRIPTION
**Pull request by yh-luo**
Hi,
thank you for the convenient tobii controller! It is a great help to my research 👍 

Tobii provided calibration validation [add-ons](https://github.com/tobiipro/prosdk-addons-python) on GitHub and I tried to integrate it with the `tobii_controller` class. It works smoothly on v1.85.3 with Python 2 and v1.90.2 with Python 3.
The usage is similar to `run_calibration` as illustrated in `sample06.py`. Hope that helps describing the quality of eye-tracking data!

Cheers,
Yu-Han

### CODE REVIEW

**Comment by hsogo** [comment]
Thank you for your pull request. This seems nice :smiley:
I think, however, that `prosdk-addons-python` package should not be included in `tobii_controller` but installed separately.

**Comment by yh-luo** [comment]
Thank you for the feedback!
I've removed the `prosdk-addons-python` package. But the module does not work on Python 2 (because of `math.nan`), so `math` is additionally imported to check if `math.nan` exists, and if not, it will be assigned.
I'm quite a beginner in Python. If there are any problems, please let me know. I will be happy to revise the codes!

**Comment by hsogo** [comment]
Sorry for my late reply.  I myself don't own Tobii eye trackers and I have to borrow one to test codes.

Yesterday I tested your code and noticed that calibration results doesn't shown appropriately.   In addition, validation target jumps too quickly.  For reference, participant have to fixate on the validation target for a while in Tobii's validation tool.

Unfortunately, I have return Tobii now and I'm afraid that I will make you wait so long again to test your code even if you kindly fix these issues.  So, please let me close this pull request.

Thank you.

**Comment by yh-luo** [comment]
Thank you for testing the code and the feedbacks! I would improve the codes and keep the repository as a simple plugin for the `psychopy_tobii_controller`, thank you for the great works again 😃   
As a side note, I wondered whether you tested the code with Python 3 ? I tested the `sample06.py` in Python 3 and encountered errors. Because `MethodType` in Python 3 does not require the `class` argument, `set_custom_calibration` does not work in Python 3 environment, causing the problem of the script.

**Comment by hsogo** [comment]
Thank you for the information.   I haven't tested the code with Python3.

As you have pointed out, `MethodType()` requires only two arguments in Python3.  I think that modifying definition of `set_custom_calibration()` as follows will fix this issue.

```
    def set_custom_calibration(self, func):

        import sys
        if sys.version_info[0] == 2:
            self.update_calibration = types.MethodType(func, self, tobii_controller)
        else:
            self.update_calibration = types.MethodType(func, self)

``` 

Please let me know if this works 😃

**Pull request closed without merging**
